// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rldrcongresqaqbebceb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsZHJjb25ncmVzcWFxYmViY2ViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MzA4MTYsImV4cCI6MjA3MzAwNjgxNn0.lEyfko2_9YqtYG9H8ET8HMZOgplxJND1zm8zcS8AnJo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});